"""
Câu 2 : Viết chương trình cho phép người dùng nhập vào số lượng người muốn nhập vào hệ thống.
Tạo ra số lượng đối tượng thuộc lớp human tương ứng. Sau đó tiến hành nhập thông tin, từng người
(họ tên, năm sinh, ....) và lưu trong các biến thuộc lớp human.
Ví dụ :
Nhập số lượng người : 2
Nhập họ tên nguời thứ 1 : .....
Nhập năm sinh người thứ 1 : ...
Nhập quê quán người thứ 1: ...
Nhập nghề nghiệp người thứ 1: ...
Nhập họ tên người thứ 2: ...
...

Sau đó in thông tin của các người dùng đó ra màn hình và sử dụng hàm work() để cho biết thông tin
về nơi làm việc của những người đó với diachicoquan của từng người do sinh viên tự nhập vào.
"""
